from enum import StrEnum

class FactStatus(StrEnum):
    VERIFIED="VERIFIED"; PROBABLE="PROBABLE"; DISPUTED="DISPUTED"
    POSSIBLE="POSSIBLE"; UNSUPPORTED="UNSUPPORTED"; UNKNOWN="UNKNOWN"

class ClaimEpistemicStatus(StrEnum):
    ASSERTED="ASSERTED"; REPORTED="REPORTED"; RUMORED="RUMORED"
    INFERRED="INFERRED"; DENIED="DENIED"; UNCERTAIN="UNCERTAIN"

class MissingnessStatus(StrEnum):
    ABSENT="ABSENT"; UNKNOWN="UNKNOWN"; NOT_RECORDED="NOT_RECORDED"
    LOST_SOURCE="LOST_SOURCE"; UNOBSERVABLE="UNOBSERVABLE"
    PARTIALLY_OBSERVED="PARTIALLY_OBSERVED"

class JobStatus(StrEnum):
    QUEUED="QUEUED"; RUNNING="RUNNING"; SUCCEEDED="SUCCEEDED"; FAILED="FAILED"
    CANCELLED="CANCELLED"; DEGRADED="DEGRADED"; BLOCKED_EXTERNAL="BLOCKED_EXTERNAL"
    BLOCKED_PRIVACY_POLICY="BLOCKED_PRIVACY_POLICY"; BLOCKED_BUDGET_POLICY="BLOCKED_BUDGET_POLICY"

class SourceRelationType(StrEnum):
    CITES="CITES"; COPIES="COPIES"; DERIVES_FROM="DERIVES_FROM"; TRANSLATES="TRANSLATES"
    EDITS="EDITS"; ABRIDGES="ABRIDGES"; REPRINTS="REPRINTS"; POSSIBLY_DEPENDS_ON="POSSIBLY_DEPENDS_ON"

class ObservationType(StrEnum):
    DIRECT="DIRECT"; PROXY="PROXY"; ADMINISTRATIVE="ADMINISTRATIVE"; ESTIMATE="ESTIMATE"

class PrivacyClass(StrEnum):
    LOCAL_ONLY="LOCAL_ONLY"; LOCAL_PREFERRED="LOCAL_PREFERRED"; CLOUD_ALLOWED="CLOUD_ALLOWED"

class RoutingMode(StrEnum):
    FIXED="FIXED"; PREFERRED_WITH_FALLBACK="PREFERRED_WITH_FALLBACK"; AUTO="AUTO"

class AcquisitionMode(StrEnum):
    AUTO_DOWNLOAD="AUTO_DOWNLOAD"; METADATA_AND_LINK="METADATA_AND_LINK"
    DISCOVERY_ONLY="DISCOVERY_ONLY"; BLOCKED_RIGHTS="BLOCKED_RIGHTS"; BLOCKED_AUTH="BLOCKED_AUTH"
