from __future__ import annotations
from typing import Protocol, Any

class SourceRepository(Protocol):
    def create_source(self, **data) -> Any: ...
    def create_version(self, **data) -> Any: ...
    def get_version_by_hash(self, sha256: str) -> Any | None: ...

class ClaimRepository(Protocol):
    def create(self, **data) -> Any: ...
    def get(self, claim_id: str) -> Any | None: ...
    def list_by_source_version(self, source_version_id: str) -> list[Any]: ...

class EntityRepository(Protocol):
    def merge(self, canonical_entity_id: str, source_entity_ids: list[str], reason: str) -> None: ...
    def split(self, source_entity_id: str, assignments: dict[str, str], reason: str) -> None: ...

class DependencyRepository(Protocol):
    def mark_descendants_stale(self, upstream_ref: str) -> list[str]: ...
